### ISSUE TITLE
Status?A

### ISSUE THREAD

**Issue by prologic** [mlctrez/goapp-mdc#1]
Are you still maintaining this?

I'd like to use it for a PWA App for [Salty IM](https://salty.im) using [Go-App](https://go-app.dev)

If you are, I'll give this a go 👌

**Comment by mlctrez** [comment]
@prologic   

 I could probably put some more effort into finishing / finalizing work on this. I was looking for some feedback on how useful this would be before I put any more effort into it. 

There is also some demo code at [goapp-mdc-demo](https://github.com/mlctrez/goapp-mdc-demo) if you have not already found it. 
The Readme on that repo has a live demo.

**Comment by prologic** [comment]
> @prologic
> 
> I could probably put some more effort into finishing / finalizing work on this. I was looking for some feedback on how useful this would be before I put any more effort into it.

Could you? 🤗 Please 🙇‍♂️

I'm wanting to use it for building a PWA app for [Salty IM](https://salty.im) and I have an [experimental branch](https://git.mills.io/prologic/saltyim/src/branch/material-design-exp) up where I was "playing around" with your library. So far so good, but honestly I'm pretty rubbish at UI/UX 😅

> There is also some demo code at [goapp-mdc-demo](https://github.com/mlctrez/goapp-mdc-demo) if you have not already found it. The Readme on that repo has a live demo.

No I did not, I'll take a gander now and see what I can "rip off" (hope you don't mind)

BTw, would you be interested in helping me build this app?

**Comment by mlctrez** [comment]
> 
> Could you? :hugs: Please :bowing_man:
>
Absolutely, also willing to help in building the app where I can.
> 
> I'm wanting to use it for building a PWA app for [Salty IM](https://salty.im) and I have an [experimental branch](https://git.mills.io/prologic/saltyim/src/branch/material-design-exp) up where I was "playing around" with your library. So far so good, but honestly I'm pretty rubbish at UI/UX :sweat_smile:
> 
I'l also admit I'm pretty rubbish at UI/UX. :smile:  
> > There is also some demo code at [goapp-mdc-demo](https://github.com/mlctrez/goapp-mdc-demo) if you have not already found it. The Readme on that repo has a live demo.
> 
> No I did not, I'll take a gander now and see what I can "rip off" (hope you don't mind)

I saw your question about app updates in go-app.  Take a look at [appupdate.go](https://github.com/mlctrez/goapp-mdc-demo/blob/master/demo/appupdate.go) in the demo code for an example.

> 
> BTw, would you be interested in helping me build this app?

:+1:

**Comment by prologic** [comment]
@mlctrez Oh man if you could jump on the project with us that would be great! At this point I'd be just happy if we got a working PWA of what the command-line client and tui does, then we can iterate on that 👌 Are you on Signal per chance?

**Comment by mlctrez** [comment]
@prologic   -- Send me an email at mlctrez@gmail.com and I'll get you my contact information for signal.
